services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    network_mode: "host"
    ports:
      - 18888:18888
  